#cloud-config
groups:
  - debian: [root, sys]

users:
  - default
  - name: ${LINUX_USER_DEVOPS_4m_debian}
    gecos: ${LINUX_USER_DEVOPS_4m_debian}
    shell: /bin/bash
    primary_group: ${LINUX_USER_DEVOPS_4m_debian}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    lock_passwd: false
    ssh_authorized_keys: ${LINUX_SSH_KEY_4m_debian}

chpasswd:
  expire: false
  users:
    - name: ${LINUX_USER_DEVOPS_4m_debian}
      password: ${LINUX_USER_PW_DEVOPS_4m_debian}
      type: text

runcmd:
  - sudo apt-get update
  - curl -fsSL get.docker.com | bash
  - sudo usermod -aG docker ${LINUX_USER_DEVOPS_4m_debian}
  - apt install -y zsh
  - echo '${LINUX_USER_DEVOPS_4m_debian}:${LINUX_USER_PW_DEVOPS_4m_debian}' | sudo chpasswd
  # May want to change this to `chsh -s $(which zsh)` -- because:
  # `chsh -s /usr/bin/zsh` may not work on some distros, maybe on mac even. It is better to run `chsh -s $(which zsh)`, because some distros change where some binary executables are stored -- wantyapps
  # - chsh -s /usr/bin/zsh
  - chsh -s `which zsh` ${LINUX_USER_DEVOPS_4m_debian}
  - zsh
  - sudo -u ${LINUX_USER_DEVOPS_4m_debian} sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
