#cloud-config
groups:
  - debian: [root, sys]

users:
  - default
  - name: ${LINUX_USER_DEVOPS_3M}
    gecos: ${LINUX_USER_DEVOPS_3M}
    shell: /bin/bash
    primary_group: ${LINUX_USER_DEVOPS_3M}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    lock_passwd: false
    ssh_authorized_keys:
      ssh_public_id_ed25519_021024_server3m: ${LINUX_SSH_KEY_3M}

runcmd:
  - sudo NEEDRESTART_MODE=a apt-get dist-upgrade --yes
  - sudo DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y
  - sudo apt-get -y update
  - sudo apt-get -y install apt-transport-https ca-certificates curl
    software-properties-common net-tools
  - curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable"
  - sudo apt-get update
  - curl -fsSL get.docker.com | bash
  - sudo usermod -aG docker ${LINUX_USER_DEVOPS_3M}
  - sudo apt install -y zsh
  - sudo chsh -s /usr/bin/zsh
  - sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  # - sudo apt-cache policy docker-ce && apt-get -y install docker-ce docker-ce-cli containerd.io
  # - sudo usermod -aG docker ${LINUX_USER_DEVOPS_3M}
  # - sudo curl -SL
  #   https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-linux-x86_64
  #   -o /usr/local/bin/docker-compose
  # - sudo chmod +x /usr/local/bin/docker-compose
  ##### START zsh section
  # https://bluevps.com/blog/how-to-install-oh-my-zsh-on-ubuntu-2204
  # - sudo apt clean
  # - sudo apt install -y git zsh
  # - sudo chsh -s /usr/bin/zsh
  # - sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  # to add zsh-autosuggestions to ~/.zshrc
  # Note: first install zsh-autosuggestions
  # Note: this sed command is not idempotent -- may need improvement
  # - sed -i -E '/plugins=\(([^)]+)\)/s//plugins=(\1 zsh-autosuggestions)/'
  ##### END zsh section
  # - echo 'deb http://download.opensuse.org/repositories/shells:/zsh-users:/zsh-autosuggestions/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/shells:zsh-users:zsh-autosuggestions.list
  # - curl -fsSL https://download.opensuse.org/repositories/shells:zsh-users:zsh-autosuggestions/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/shells_zsh-users_zsh-autosuggestions.gpg > /dev/null
  # - sudo apt update
  # - sudo apt install zsh-autosuggestions
